### ISSUE TITLE
no aes-ni

### ISSUE THREAD

**Issue by cryptoballs** [MoneroOcean/xmr-node-proxy#1]
For machines without aes-ni using Snipa22's version of xmr-node-proxy he has option to replace node-multi-hashing-aesni with node-multi-hashing

Do you have any similar option for node-cryptonight-hashing?

Tried to update proxy to your fork and could not build successfully, think this may be the issue.

**Comment by MoneroOcean** [comment]
Thanks for report! I put possible fix for that. Could you please try to build it again?

**Comment by grunjol** [comment]
I can confirm the non-AESNI node-cryptonight-hashing is compiling and working

**Comment by MoneroOcean** [comment]
Great! Thanks for checking!

**Comment by cryptoballs** [comment]
Just compiled & it's working for me too. Sorry for my delayed response. Thanks for promptly providing the needed fix!

**Comment by MoneroOcean** [comment]
Thank you very much for checking.
