### ISSUE TITLE
fail update to 0.10.0

### ISSUE THREAD

**Issue by qutimqqcom** [MoneroOcean/xmr-node-proxy#100]
How fix it ?

make: Entering directory '/home/pr/xmr-node-proxy/node_modules/cryptonight-hashing/build'
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/asm/cn_main_loop.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/asm/CryptonightR_template.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/CryptonightR_gen.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn_gpu_ssse3.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/common/cpu/Cpu.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/common/cpu/BasicCpuInfo.o
  CXX(target) Release/obj.target/cryptonight-hashing/multihashing.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/extra.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/Mem.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/Mem_unix.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/c_blake256.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/c_groestl.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/c_jh.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/c_skein.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/common/crypto/keccak.o
  CXX(target) Release/obj.target/cryptonight-hashing/RandomWOW/src/aes_hash.o
In file included from /usr/lib64/gcc/x86_64-suse-linux/8/include/x86intrin.h:45,
                 from ../RandomWOW/src/intrin_portable.h:89,
                 from ../RandomWOW/src/soft_aes.h:32,
                 from ../RandomWOW/src/aes_hash.cpp:29:
/usr/lib64/gcc/x86_64-suse-linux/8/include/wmmintrin.h: In function ‘rx_vec_i128 aesenc(rx_vec_i128, rx_vec_i128) [with booloft = false]’:
/usr/lib64/gcc/x86_64-suse-linux/8/include/wmmintrin.h:61:1: error: inlining failed in call to always_inline ‘__m128i _mm_aenc_si128(__m128i, __m128i)’: target specific option mismatch
 _mm_aesenc_si128 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
In file included from ../RandomWOW/src/aes_hash.cpp:29:
../RandomWOW/src/soft_aes.h:40:65: note: called from here
  return soft ? soft_aesenc(in, key) : rx_aesenc_vec_i128(in, key);
                                                                 ^
make: *** [cryptonight-hashing.target.mk:156: Release/obj.target/cryptonight-hashing/RandomWOW/src/aes_hash.o] Error 1
make: Leaving directory '/home/pr/xmr-node-proxy/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pr/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/libuild.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.7-1-default
gyp ERR! command "/home/pr/.nvm/versions/node/v8.11.3/bin/node" "/home/pr/.nvm/versions/node/v8.11.3/lib/node_modules/npm/no_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pr/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@9.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@9.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pr/.npm/_logs/2019-06-24T09_54_20_573Z-debug.log
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command

pr@xnp166:~/xmr-node-proxy$ gcc --version
gcc (SUSE Linux) 8.2.1 20180831 [gcc-8-branch revision 264010]

**Comment by rampso** [comment]
I am also having this issue, have you found any solutions?

**Comment by qutimqqcom** [comment]
compiles successfully only on processors with aes support
gcc (SUSE Linux) 9.1.1
Name           : boost-devel
Version        : 1.69.0-1.3

**Comment by qutimqqcom** [comment]
v0.11.0
compiled successfully
cpu  sse
gcc 7
boost 69
