### ISSUE TITLE
does it support the XMR fork on november 30? can it still be used for mining RandomX?

### ISSUE THREAD

**Issue by Aprrentice** [MoneroOcean/xmr-node-proxy#109]
does it support the XMR fork on november 30? can it still be used for mining RandomX?

**Comment by MoneroOcean** [comment]
Yes. It supports RandomX (rx/0) algo. Should auto switch on Nov 30 automatically from cn/r to rx/0 as well.

**Comment by Aprrentice** [comment]
good. so there is no update for XNP, will keep pointing the miners to it as it is?

**Comment by MoneroOcean** [comment]
Yes.

**Comment by Aprrentice** [comment]
so in config the algo need to be changed from cn/r tp rx/0 to mine randomx?

"algo":  "rx/0",

thanks.

**Comment by MoneroOcean** [comment]
Yes, you can do that after fork. Before fork you can put "algo": [ "cn/r", "rx/0" ], to make algo switch automatic.

**Comment by MrCook1es** [comment]
Hi, is it right?

      "blob_type": "cryptonote",

in my config?
or i have to make changes?
