### ISSUE TITLE
use XNP v0.15.2 + xmrig v5.1.1-mo1, rx/0 LOW DIFF SHARE

### ISSUE THREAD

**Issue by qutimqqcom** [MoneroOcean/xmr-node-proxy#114]
when switch algo to rx/0 all miners fails with error
low diff share
how to fix ? what to fix ? miner or proxy ?

**Comment by pr0vieh** [comment]
Proxy Config Change: 
"algo": "cn/r", to "algo": "rx/0",

this helps 4 me

**Comment by qutimqqcom** [comment]
> 
> 
> Proxy Config Change:
> "algo": "cn/r", to "algo": "rx/0",
> 
> this helps 4 me

For what  u comment ?  
      "algo": [ "rx/0" ],
      "blob_type": "cryptonote",

**Comment by djfinch** [comment]
Is xmrig 2.14.1 typo? AFAIK this release is pretty old and does not support RX for XMR...

**Comment by qutimqqcom** [comment]
> 
> 
> Is xmrig 2.14.1 typo? AFAIK this release is pretty old and does not support RX for XMR...

THX but  i misstake

 * ABOUT        XMRig/5.1.1-mo1 gcc/5.3.1
 * LIBS         libuv/1.31.0 hwloc/1.10.0

**Comment by qutimqqcom** [comment]
Ich habs !!!  

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 3.5.1
Local PM2 version: 4.2.0
