### ISSUE TITLE
RandomV not working?!

### ISSUE THREAD

**Issue by pr0vieh** [MoneroOcean/xmr-node-proxy#117]
this is happens when RandomV(rx/v) Mining is ongoing... Miners Connect Disconnect in a loop and Stacking... i have over 100 Miners Connected but i have only 17 ;)

1|proxy  | 2019-12-24 17:53:33:409 +01:00: Starting a new worker
1|proxy  | 2019-12-24 17:53:33:468 +01:00: Worker 32050 is online
1|proxy  | 2019-12-24 17:53:33:748 +01:00: Started server on port: 4444
1|proxy  | 2019-12-24 17:53:36:457 +01:00: The proxy currently has 51 miners connected at 101048 h/s (gulf.moneroocean.stream/100.00%) with an average diff of 5420
1|proxy  | 2019-12-24 17:53:36:946 +01:00: Error: Unknown RandomX algo
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at hash_func (/root/xmr-node-proxy/lib/xmr.js:135:60)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at Object.processShare (/root/xmr-node-proxy/lib/xmr.js:356:20)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at handleMinerData (/root/xmr-node-proxy/proxy.js:1189:49)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at handleMessage (/root/xmr-node-proxy/proxy.js:1418:13)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at Socket.<anonymous> (/root/xmr-node-proxy/proxy.js:1476:25)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at emitOne (events.js:116:13)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at Socket.emit (events.js:211:7)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at addChunk (_stream_readable.js:263:12)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at readableAddChunk (_stream_readable.js:246:13)
1|proxy  | 2019-12-24 17:53:36:946 +01:00:     at Socket.Readable.push (_stream_readable.js:208:10)
1|proxy  | 2019-12-24 17:53:36:959 +01:00: Worker 31958 died with code: 1, and signal: null
1|proxy  | 2019-12-24 17:53:36:959 +01:00: Starting a new worker
1|proxy  | 2019-12-24 17:53:37:067 +01:00: Worker 32075 is online
1|proxy  | 2019-12-24 17:53:37:344 +01:00: Started server on port: 4444
1|proxy  | 2019-12-24 17:53:44:787 +01:00: Error: Unknown RandomX algo
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at hash_func (/root/xmr-node-proxy/lib/xmr.js:135:60)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at Object.processShare (/root/xmr-node-proxy/lib/xmr.js:356:20)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at handleMinerData (/root/xmr-node-proxy/proxy.js:1189:49)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at handleMessage (/root/xmr-node-proxy/proxy.js:1418:13)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at Socket.<anonymous> (/root/xmr-node-proxy/proxy.js:1476:25)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at emitOne (events.js:116:13)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at Socket.emit (events.js:211:7)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at addChunk (_stream_readable.js:263:12)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at readableAddChunk (_stream_readable.js:246:13)
1|proxy  | 2019-12-24 17:53:44:787 +01:00:     at Socket.Readable.push (_stream_readable.js:208:10)
1|proxy  | 2019-12-24 17:53:44:795 +01:00: Worker 32075 died with code: 1, and signal: null
1|proxy  | 2019-12-24 17:53:44:795 +01:00: Starting a new worker
1|proxy  | 2019-12-24 17:53:44:856 +01:00: Worker 32165 is online
1|proxy  | 2019-12-24 17:53:45:157 +01:00: Started server on port: 4444
1|proxy  | 2019-12-24 17:53:46:526 +01:00: Error: Unknown RandomX algo
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at hash_func (/root/xmr-node-proxy/lib/xmr.js:135:60)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at Object.processShare (/root/xmr-node-proxy/lib/xmr.js:356:20)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at handleMinerData (/root/xmr-node-proxy/proxy.js:1189:49)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at handleMessage (/root/xmr-node-proxy/proxy.js:1418:13)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at Socket.<anonymous> (/root/xmr-node-proxy/proxy.js:1476:25)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at emitOne (events.js:116:13)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at Socket.emit (events.js:211:7)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at addChunk (_stream_readable.js:263:12)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at readableAddChunk (_stream_readable.js:246:13)
1|proxy  | 2019-12-24 17:53:46:526 +01:00:     at Socket.Readable.push (_stream_readable.js:20

**Comment by MoneroOcean** [comment]
Try to do ```rm -rf node_mopdules; npm install```

**Comment by pr0vieh** [comment]
a Fresh Install of XNP also solves this Problem!
tanks for the fast replay 👍
