### ISSUE TITLE
Stellite upcoming variant change

### ISSUE THREAD

**Issue by djfinch** [MoneroOcean/xmr-node-proxy#12]
Hi guys,

Will XNP work after their change? I suppose some amendments will be needed, right?
https://github.com/stellitecoin/Stellite/commit/d4984cce1a4f6647db506c08e1980a9e5e297d08

Thanks!

**Comment by bobbieltd** [comment]
Here is new algorithm for Stellite (xmrig and xmr-stak will support it). cryptonight-xtl (or cryptonight variant xtl )—> https://github.com/xmrig/xmrig/issues/581#issuecomment-384591672
MO, will you support this coin ?

**Comment by bobbieltd** [comment]
By the way, it’s Monero’s fork (Electroneum’s fork), there is not “forknote” issue here.

**Comment by MoneroOcean** [comment]
It will be supported only as part of cryptonight utils (later as part of cn-heavy update). MO XNP will not support this out-of-the box since MO pool does not support XTL (because miners can't switch between variants unless there is config change).

**Comment by MoneroOcean** [comment]
MO XNP proxy primary goal is to support MO pool and not support all these endless altcoins that aer not supported by MO pool.

**Comment by djfinch** [comment]
Well, I have it now just as failover to their community.stellite.cash pool and planning to switch it all as their devs doing exactly what they promised, community is growing and market (TO currently) look good. So there are two option ... Support XTL on MO as well or going away.
