### ISSUE TITLE
what does this error mean

### ISSUE THREAD

**Issue by Aprrentice** [MoneroOcean/xmr-node-proxy#123]
Getting this error on the proxy monit a lot.
what does it mean? and how to resolve it?

Malformed message from 172.215.18.100 Message: POST /ws/v1/cluster/apps/new-application

thanks.

![XMR](https://user-images.githubusercontent.com/41146763/77916725-36548a80-72a2-11ea-9171-d8a43f1ffa71.PNG)

**Comment by djfinch** [comment]
Just couple of robots trying to figure out which service is running on your IP/port...
They just sending common messages and waiting for the answer...
You can ignore them (in case it's not flooding your connection a lot) or ban specific IP or IP range via host.deny, ipfw, ufw or whatever your OS use. Alternatively you can whitelist pools&miners IPs and block everything else...
