### ISSUE TITLE
how to solve this http interface error

### ISSUE THREAD

**Issue by Aprrentice** [MoneroOcean/xmr-node-proxy#124]
Getting this error on the logs:

![image](https://user-images.githubusercontent.com/41146763/77917759-9ef03700-72a3-11ea-8905-2466b4ce865b.png)

if I set it to false, the proxy works fine. tries different ports, same error. the IP of the http is set to the IP of the server where XNP is running.

Please advise.
thanks.

**Comment by djfinch** [comment]
ErrorADDRessNOTAVAILable... Use different port for web API because this one is already occupied by different service...

**Comment by Aprrentice** [comment]
I used multiple ports but always getting the erroe. am trying EC2 ubuntu.

**Comment by djfinch** [comment]
I had zero issues with EC2 t2.micro in the past... Are those ports allowed in AWS console/security group? Also, change IP to 0.0.0.0, dashboard will be accessible on all interfaces...

**Comment by Aprrentice** [comment]
ok..
thanks.
found out the problem.
