### ISSUE TITLE
BigInt is not defined

### ISSUE THREAD

**Issue by Turosik** [MoneroOcean/xmr-node-proxy#139]
I got a problem after last update proxy was just spamming an error "BigInt is not defined"
Solved by changing "bignum" version in package.json file from ^0.12.5 to ^0.13.1
May be developers should check that and make changes in the repository

**Comment by MoneroOcean** [comment]
I will update it. Thank you. Normally this should be resolved by using node v14 (I made changes in install script). Will apply your suggestion too. Thank you!

**Comment by metal3d** [comment]
Sorry but it is not fixed.
