### ISSUE TITLE
High number of connections to the pool from XNP

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/xmr-node-proxy#16]
Debugging https://github.com/MoneroOcean/nodejs-pool/issues/21 , I found out those connections from the XNP.
It happens with the config.json --> pool with default : true + no miners to that pool. It keeps creating new miners at pool.

**Comment by MoneroOcean** [comment]
H, very interesting.

**Comment by bobbieltd** [comment]
I’m trying to debug at XNP but I can not recreate that effect.
So my guess : Someone tried XNP for fun. He made wrong config and proxy keeps dying after pool connections. He doesn’t care to stop proxy. Or with the coin forks, the old proxy is not compatible with new block template and he can not access to proxy anymore to change. It can make proxy connecting and keeping crashed.

Solution : banning wrong / for fun proxy with firewall.

I will reopen the issue if I can find anything new. I think your recent fix already solved the issue. This one is not issue. Non working miners will be deleted after time out. No bad effects.
