### ISSUE TITLE
Feature Request: Adding of backup pool

### ISSUE THREAD

**Issue by caradex** [MoneroOcean/xmr-node-proxy#17]
Xmr-node-proxy should allow configuring of a backup pool so whenever the primary pool goes down, xnp will connect to the backup pool. As of now, there is a possibility to configure multiple pools but xnp splits the hashing power to all the pools configured.

**Comment by MoneroOcean** [comment]
Thanks for suggestion! Very useful one. At least I need to check if multiple pool works fine in case one of them is dead.

**Comment by MoneroOcean** [comment]
Backup pool feature was added in https://github.com/MoneroOcean/xmr-node-proxy/commit/2edd2c9541ee7ee7ac853c2437650a94666c8f6c commit for pools that have zero share in config.
