### ISSUE TITLE
Warning during npm update command execution

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#18]
Hello,
Just a little information
Here is a warning that appears during any proxy update.

`nodeproxy@srvxmr01:~/xmr-node-proxy$ npm update

> cryptoforknote-util@0.9.1 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR`

Thanks.
Alexandre

**Comment by MoneroOcean** [comment]
You just need to do `unset NVM_NODEJS_ORG_MIRROR` shell command if you do not want to see these warning. Not sure if it can be possible to fix on my side.
