### ISSUE TITLE
Proxy crash and memory saturation

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#19]
Hello,
Yesterday I updated my proxy for "backup pool".
And today I had two crashes with memory saturation.

The "Destory not needed socket" commit is to solve the problem?

Thanks,
Alexandre

**Comment by MoneroOcean** [comment]
Yes it can solve it if you have log periods of pool connection issues. Can you please check that it helps or show proxy log if that is not too sensitive to share?

**Comment by alexdaums** [comment]
Hello,
My proxy crashed last night.
Here are the different log files.

Thanks
[proxy-error-1.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1973436/proxy-error-1.log)
[backup.txt](https://github.com/MoneroOcean/xmr-node-proxy/files/1973439/backup.txt)

**Comment by MoneroOcean** [comment]
OK. Thank you. Will take a look.

**Comment by MoneroOcean** [comment]
OMG. So many errors from supportxmr pool in log. Yes, looks like socket is not completely cleared and also I should put extra delay to avoid that error spam.

**Comment by MoneroOcean** [comment]
I simplified pool connection code (https://github.com/MoneroOcean/xmr-node-proxy/commit/5526a206254dfde8694c0721f6e805d64c766a19) and added more detailed error messages. Could you please update (git pull) and send me error log as before if situation will repeat? I can not reproduce this stream of supportxmr timeout connection errors (it is quite strange why timeout are so tightly packed in time as well).

**Comment by alexdaums** [comment]
Ok!
Update completed ... now wait and see.
Thanks

**Comment by alexdaums** [comment]
So far it's working fine.
The errors of "pool.supportxmr.com" do not seem to impact the proxy.
Attached this afternoon's logs. They're lighter than the old ones!

[proxy-error-1.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1974977/proxy-error-1.log)

**Comment by MoneroOcean** [comment]
Yeah, more testing is needed.

**Comment by bobbieltd** [comment]
Sorry to hijack your issue. I want to have your opinion too because you are using it.
@MoneroOcean I don’t understand your connect2 to balance to failover pool. But I guess you need to retake new block template from new connected pool and reject all old jobs on the failed pool.
The way to implement balancing is too complicated. Why don’t we add another hostname2, if hostname failed, switch to hostname2,3,4 ...

**Comment by MoneroOcean** [comment]
@alexdaums still working fine?

**Comment by alexdaums** [comment]
@MoneroOcean 
Yeah, it works fine.
The memory consumption is stable and in the same value as before the bug.
Thanks

**Comment by alexdaums** [comment]
I have a problem with this morning's update.
Proxy often restarts itself
[proxy-error-1.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1977436/proxy-error-1.log)

**Comment by bobbieltd** [comment]
@MoneroOcean : For info, I have those message -1, unauthenticaer with two pools in config. Two pools with different coins that I don’t have any workers + default : true. However, it happened only once. Hope that helps.

**Comment by MoneroOcean** [comment]
@alexdaums Thanks for report. I rolled back change that seems to be causing it: https://github.com/MoneroOcean/xmr-node-proxy/commit/97b3869b1030117560c57da37d67c7cbc2497549

**Comment by MoneroOcean** [comment]
@alexdaums also I would like to suggest you to change pool.supportxmr.com to pool.monero.hashvault.pro. It may work better for you (less Unauthenticated errors that I think are responsible for out of memory issues). I do not say we should not look into them, but at least it may solve your particular case.

**Comment by alexdaums** [comment]
@MoneroOcean 

1. xmr-node-proxy run on a VM with 2 vCPU et 1GB RAM.
![htop xmr-node-proxy](https://user-images.githubusercontent.com/1036127/39676921-caa9d88c-5172-11e8-877e-357e35fbfc5c.jpeg)

2. I updated and deleted the logs 1 hour ago.
[proxy-error-1.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1977941/proxy-error-1.log)

3. For the backup pool change I will think about it. But I still have some money at pool.supportxmr.com. 
And xmr-node-proxy is currently working very well.
The modifications made are very good.
Thank you very much!
![xmr-node-proxy](https://user-images.githubusercontent.com/1036127/39676975-d2f56474-5173-11e8-8149-bb4fc32efe8b.jpeg)

**Comment by alexdaums** [comment]
Hello,
I switched my backup pool to pool.monero.hashvault.pro.
And the proxy-out-1.log stays empty.

**Comment by MoneroOcean** [comment]
Our or error?

**Comment by alexdaums** [comment]
Sorry ... error log stay empty

**Comment by alexdaums** [comment]
For me we can close this issue.

**Comment by MoneroOcean** [comment]
OK, thanks!
