### ISSUE TITLE
Proxy Update Information

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#24]
Hello,

To make the updates you give us the following commands:
`git pull`
`npm update`

Why not use the update.sh script included?

Thanks

**Comment by MoneroOcean** [comment]
Good point! Will add it.

**Comment by alexdaums** [comment]
update.sh is already in your github.
Snipa22 created it.

**Comment by MoneroOcean** [comment]
Yeah, just noticed it. Thank you. Updated instructions and added tag to utils so update script will work more intelligently.

**Comment by alexdaums** [comment]
Can you add the command to make it executable?
`chmod +x ./update.sh`
