### ISSUE TITLE
Update error v0.1.5

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#27]
Hello,
Here is the error I have when trying to update to v0.1.5
[Log update proxy.txt](https://github.com/MoneroOcean/xmr-node-proxy/files/1980284/Log.update.proxy.txt)
 Thanks

**Comment by MoneroOcean** [comment]
Please try again. Just fixed it.

**Comment by alexdaums** [comment]
Thanks, it's okay now.
