### ISSUE TITLE
Need for precision on the backup pool.

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#29]
Hello,

At this moment I mine for "supportxmr" to empty my accumulated currency. 
Then back to MO which is much more dynamic.

This morning supportxmr had a problem and I think the backup pool (MO) was not working properly.
Here are my log files at the time of the problem.
If anyone can explain to me why there is very little share to MO when supportxmr is down?
[proxy-error-1.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1983933/proxy-error-1.log)
[proxy-out.log](https://github.com/MoneroOcean/xmr-node-proxy/files/1983934/proxy-out.log)

**Comment by MoneroOcean** [comment]
Can you please show your config (with masked wallet)? Is it possible that gulf.moneroocean.stream is not listed as backup pool (with 0 share)? These small shares still submitted to gulf.moneroocean.stream are likely dev donation pool shares.

**Comment by alexdaums** [comment]
My config file.
[config.txt](https://github.com/MoneroOcean/xmr-node-proxy/files/1984115/config.txt)

**Comment by MoneroOcean** [comment]
I see. Likely dev donation pool (also gulf.moneroocean.stream) conflicted and overridden the main pool. I fixed that by changing donation pool name to donations..moneroocean.stream. Please run `./update.sh` to fix that.

**Comment by alexdaums** [comment]
2018-05-08 16:17 +02:00: [MASTER] Plain pool socket connect error from donations.moneroocean.stream: Error: read ECONNRESET
2018-05-08 16:17 +02:00: [MASTER] Pool socket error from donations.moneroocean.stream: Error: read ECONNRESET
2018-05-08 16:17 +02:00: [MASTER] Pool socket closed from donations.moneroocean.stream
2018-05-08 16:17 +02:00: [MASTER] Plain pool socket connect error from donations.moneroocean.stream: Error: read ECONNRESET
2018-05-08 16:17 +02:00: [MASTER] Pool socket error from donations.moneroocean.stream: Error: read ECONNRESET
2018-05-08 16:17 +02:00: [MASTER] Pool socket closed from donations.moneroocean.stream
2018-05-08 16:17 +02:00: [MASTER] Plain pool socket connect error from donations.moneroocean.stream: Error: read ECONNRESET
2018-05-08 16:17 +02:00: [MASTER] Pool socket error from donations.moneroocean.stream: Error: read ECONNRESET

**Comment by MoneroOcean** [comment]
Hopefully it will automatically fix itself after some time after you will have DNS server update. At least it works on my system already.

**Comment by MoneroOcean** [comment]
Proxy works fine despite this error?

**Comment by alexdaums** [comment]
DNS OK.
XNP works fine.

**Comment by MoneroOcean** [comment]
What IP donations.moneroocean.stream resolves to from your system?

`ping donations.moneroocean.stream` ?

**Comment by alexdaums** [comment]
ping donations.moneroocean.stream
PING monerooceans.stream (54.37.158.183) 56(84) bytes of data.
64 bytes from 183.ip-54-37-158.eu (54.37.158.183): icmp_seq=1 ttl=53 time=41.4 ms
64 bytes from 183.ip-54-37-158.eu (54.37.158.183): icmp_seq=2 ttl=53 time=38.4 ms
64 bytes from 183.ip-54-37-158.eu (54.37.158.183): icmp_seq=3 ttl=53 time=39.0 ms

**Comment by MoneroOcean** [comment]
Hm, do not why it does not work in this case. Lets wait till tomorrow. Maybe it is some OVH provider glitch on my side.

**Comment by MoneroOcean** [comment]
Yeah, no idea at this moment. Can you please try it tomorrow as well?

**Comment by alexdaums** [comment]
I'm really sorry! 
But I found the problem and it's coming from my network.
It was my firewall stormshield that was blocking the connection.
I ask myself the question is that it is the word "donations" that causes the block?

**Comment by MoneroOcean** [comment]
Hm, interesting. I will rename it to some other name :) Thanks for report!

**Comment by alexdaums** [comment]
Try devshares.moneroocean.stream

**Comment by MoneroOcean** [comment]
OK. Changed name. Please check.

**Comment by alexdaums** [comment]
With "devshare" it works perfectly!
The firewall is not blocking.

**Comment by MoneroOcean** [comment]
Big thanks for testing this :)
