### ISSUE TITLE
Cant connect to proxy

### ISSUE THREAD

**Issue by flyawayfromhere** [MoneroOcean/xmr-node-proxy#30]
Tryed on two servers (centos and ubuntu)
Proxy set well, everything running, but when i try to test connection with something like
`test = new WebSocket("wss://myproxydomain.com:8443");`
or 
`test = new WebSocket("ws://myproxydomain.com:8080");`
i have 
`failed: Error during WebSocket handshake: Unexpected response code: 200`
```
Status Code: 200 OK
Content-Length: 19
```
Same story when i use nginx upstream

I have a feeling that i done something completely wrong, but i cant get what.
Any help?

**Comment by MoneroOcean** [comment]
It is TCP/IP Stratum proxy and not web socket proxy. For web socket proxy you need to look into https://github.com/cazala/coin-hive-stratum

**Comment by flyawayfromhere** [comment]
Oh my, thank you!!!
