### ISSUE TITLE
Workers got deleted before inactivityTime

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/xmr-node-proxy#31]
I have a user report that even he put high inactivityTime but the proxy still deleted old miners.
He also want to take -1 for inactivityTime as infinite keeping worker.

Thanks for your consideration.

**Comment by MoneroOcean** [comment]
I can not reproduce this. Miners are not disconnected by proxy unless there is connection issue of course. Will keep it as FR for -1.
