### ISSUE TITLE
Fails to compile on ARM processors

### ISSUE THREAD

**Issue by manianac** [MoneroOcean/xmr-node-proxy#32]
I'm currently compiling this for a raspberry pi, and the "-m64" g++ argument is throwing errors.  Is there anyway to have this only present on x64 devices, or should I just fork the repo so I can substitute different binding.gyp files?

node-cryptonight-hashing would need updating as well, as __CRYPTONIGHT_X86_H__ woudl need re-worked

**Comment by MoneroOcean** [comment]
No ARM support at this moment. I will consider adding it later but now you can fork and replace at least cryptonight-hashing module that currently only supports x86-64 arch only.

**Comment by qutimqqcom** [comment]
+1
Raspberry Pi 3

**Comment by MoneroOcean** [comment]
Added at least aarch64 support in https://github.com/MoneroOcean/xmr-node-proxy/commit/31367ae619093e570c33c9fc977d94ea8fa0597e
Please check if it helps.

**Comment by MoneroOcean** [comment]
OK. Please reopen this if it still does not work.
