### ISSUE TITLE
Latest update broke something.

### ISSUE THREAD

**Issue by djfinch** [MoneroOcean/xmr-node-proxy#35]
Hi guys,

Latest update broke something in the proxy. Monitoring reporting up to 40 miners but I have only 8.
Also, lot of error messages in console. XNP is stock except one line in proxy.js (sorted table CSS width changed from 60% to 95%).
![screen shot 2018-05-17 at 10 44 57](https://user-images.githubusercontent.com/13107713/40166847-e2e371ba-59bf-11e8-9bc0-bdc43f9e3615.jpg)
![screen shot 2018-05-17 at 10 43 39](https://user-images.githubusercontent.com/13107713/40166889-f4e62b6e-59bf-11e8-8e76-1833c86ee943.jpg)

UPDATE:
No time to investigate, hard reset to 4b65a4a067dfdde00b5bf6355d3e3e1f57253112 temporary solved this.

**Comment by MoneroOcean** [comment]
Yes, I already fixed that. Thanks for report.

**Comment by MoneroOcean** [comment]
Should be resolve in https://github.com/MoneroOcean/xmr-node-proxy/commit/bb3ef4bd278e3349ee070c9e9589a7d0eb5ef73b

**Comment by djfinch** [comment]
Resolved. Thank you.
