### ISSUE TITLE
Add miner agent in http stats.

### ISSUE THREAD

**Issue by tinyema** [MoneroOcean/xmr-node-proxy#41]
It could be an important information when you need to upgrade clients.
Thanks for your hard work, much appreciated 👍

**Comment by MoneroOcean** [comment]
Thanks for suggestion!

**Comment by djfinch** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/13107713/41555729-db750ac8-7338-11e8-9818-67008f51646c.png)
