### ISSUE TITLE
Keep offline miners in web Dashboard

### ISSUE THREAD

**Issue by ariadarkkkis** [MoneroOcean/xmr-node-proxy#46]
Hi
I want to keep track of offline miners and check them like XMRIG-Proxy have.
It a good feature to add this option to set active miners as 1 and offline ones as 0.

**Comment by bobbieltd** [comment]
+1
@MoneroOcean Ariadarkkis found a bug with inactivityTime.
if (this.socket.destroyed){
            delete activeMiners[this.id];
            return;
}
If miners disconnect, there are not any more info about those workers (with whatever inactivity time).

**Comment by ariadarkkkis** [comment]
looking forward to fix it, ready to help and test.

**Comment by ariadarkkkis** [comment]
@moneroocean I will try and give you results

**Comment by ariadarkkkis** [comment]
@MoneroOcean I've set minerInactivityTime in config.json to 0 and it will delete offline miners same as before. The problem is here:
https://github.com/MoneroOcean/xmr-node-proxy/blob/master/proxy.js#L883

When a miner disconnect ( or a socket is destroyed ) , miner will be deleted and no stats or info will be saved anywhere. So the web panel doesnt have any information to show about that offline miner because its deleted!

**Comment by MoneroOcean** [comment]
I see. Thanks for investigation. Will apply updated fix today.

**Comment by MoneroOcean** [comment]
Please try to update and use "keepOfflineMiners": 1 in the config.

**Comment by ariadarkkkis** [comment]
@MoneroOcean ok tested. Some problems here:

1. If a miner restarts, the miner will be counted as a new miner with the same name and IP and etc. in the dashboard and will count as a Worker either. Even while it says last share some minutes or hours ago.

2. Offline miners are counted as workers in the Dashboard.

**Comment by MoneroOcean** [comment]
Got the second problem. For the first problem it will help to see output from dashboard (replace sensitive things like IP with X or Y if the denote the same address).

**Comment by ariadarkkkis** [comment]
@MoneroOcean 

1. Miner was offline.
![offline](https://user-images.githubusercontent.com/25063830/42273650-fed8be16-7f9e-11e8-8513-d9f275c93062.png)

2. Restart miner first time ( 1 restart )
![1 restart](https://user-images.githubusercontent.com/25063830/42273670-1000b41e-7f9f-11e8-95d7-01a2f8856ef0.png)

3. Restart miner second time ( 2 restarts )
![2 restarts](https://user-images.githubusercontent.com/25063830/42273682-1af1fc52-7f9f-11e8-810a-0f9f04eac55c.png)

4. after closing miner
![close](https://user-images.githubusercontent.com/25063830/42273710-3657286e-7f9f-11e8-8675-6029f4547f7e.png)

**Comment by MoneroOcean** [comment]
What is minerInactivityTime value? 0? Try to put it to default 120 seconds because there is no way I can detect that miner is no longer active unless its socket is destroyed and that can happen after some delay it seems.

If there will be duplicate miners with last share that is more than 3-4 minutes with minerInactivityTime=0 please let me know.

**Comment by MoneroOcean** [comment]
Of course I can try to avoid showing active miners with the same name in dashboard but it can break stuff for some people.

**Comment by ariadarkkkis** [comment]
Yea minerInactivityTime is 0. I will change to 120 and check again

**Comment by MoneroOcean** [comment]
I just pout fix for the second issue. Please check it as well.

**Comment by ariadarkkkis** [comment]
All fixed. Everything works fine now.
Thanks
