### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GodzSoldiers** [MoneroOcean/xmr-node-proxy#50]
Is it possible to use 2 different pools and xmr address in the config?

**Comment by djfinch** [comment]
Yep, why not... [config_example.json](https://github.com/MoneroOcean/xmr-node-proxy/blob/master/config_example.json) is using this setup (except for "username" but you can put different XMR address there). Just make sure you've correctly set "share" field...

**Comment by MoneroOcean** [comment]
Yes, that is possible.
