### ISSUE TITLE
Cannot read property 'shareTargetTime' of undefined

### ISSUE THREAD

**Issue by WaltWhitman22** [MoneroOcean/xmr-node-proxy#55]
Getting this error, and the pool restarts... This is when mining XTL on communitypool.stellite.cash 

What could be causing this? 

proxy > 2018-08-01 14:22:06:081 -04:00: TypeError: Cannot read property 'shareTargetTime' of undefined                                                             │
proxy >     at Miner.updateDifficulty (/home/nodeproxy/xmr-node-proxy/proxy.js:909:129)                                                                            │
 proxy >     at Timeout._onTimeout (/home/nodeproxy/xmr-node-proxy/proxy.js:1498:39)                                                                                │
proxy >     at ontimeout (timers.js:498:11)                                                                                                                        │
proxy >     at tryOnTimeout (timers.js:323:5)                                                                                                                      │
proxy >     at Timer.listOnTimeout (timers.js:290:5)       

proxy > 2018-08-01 14:22:06:086 -04:00: Worker 3764 died with code: 1, and signal: null

**Comment by djfinch** [comment]
Wrong config. shareTargetTime is not defined. Should contain something like this.
```
"coinSettings": {
    "xmr":{
      "minDiff": 10,
      "maxDiff": 100000,
      "shareTargetTime": 10
    }
  }
```

**Comment by WaltWhitman22** [comment]
Seemed to solve it, that I reinserted the coin settings part... Must have been some sort of error, because it was defined... But thanks anyways...

**Comment by djfinch** [comment]
You're welcome. Probably missing comma at the end of maxDiff so maxDiff was the last parsed property and shareTargetTime was not assigned then.

**Comment by Sevilla404** [comment]
Im using this config but having the same error:

    "msr":{
      "minDiff": 3000,
      "maxDiff": 300000,
      "shareTargetTime": 30
    }

**Comment by bobbieltd** [comment]
@Sevilla404 Do not use “msr” , use “xmr” for all coins. Only algo and blob need to be set for specific coin.
Masari algo : “cn/msr”, blob “cryptonote2” in config (please look at MO config example not Snipa)

**Comment by Sevilla404** [comment]
Done! Many Thanks!
