### ISSUE TITLE
errors when running update.sh

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#59]
I'm getting errors when running update.sh

error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

I am not making any changes to XNP, just a user, so i have no changes to merge

**Comment by MoneroOcean** [comment]
Try to reinstall xmr node proxy. I had to fix some commits that caused issues with other repo copies.

**Comment by djfinch** [comment]
... or try ...

```
git fetch && git reset --hard origin/master
```

**Comment by MoneroOcean** [comment]
@djfinch thanks!

**Comment by KnoAll** [comment]
@djfinch your command did the trick! update is running. thanks everyone!
