### ISSUE TITLE
API for worker list and stats

### ISSUE THREAD

**Issue by FranzDE** [MoneroOcean/xmr-node-proxy#6]
hi guys, what API do you use for see the worker list and HS stats per worker?

**Comment by Ethorsen** [comment]
I have a custom timer that output worker stats in a json file every X seconds (idea took from https://github.com/Snipa22/xmr-node-proxy/pull/111).

I might create a PR with it for MoneroOcean to review

**Comment by FranzDE** [comment]
could you please answer this question related to that discussion?

> is it required that I install apache and that I insert the file index.html inside the apache folder www ?
> Or the installation of apache is not necessary and I just place the file index.html inside the path: /home/nodeproxy/xmr-node-proxy/ ?

**Comment by Ethorsen** [comment]
Never tried the branch, but looking at the code it seems to create its own http server.  So no need of apache.

"httpEnable": true,
"httpAddress": "127.0.0.1",
"httpPort": "8080",

Set those values to whatever you need.  Then proxy should respond to http://127.0.0.1:8080/

**Comment by FranzDE** [comment]
ok, so it does not work :(
not having installed apache, I thought that the reason for not working was that...

I'll try to change port, I would not like it to be blocked on my cloud server

**Comment by FranzDE** [comment]
Now I can see the index page, it was a port issue on my cloud server.


But there is a problem:

`DataTables warning: table id=displaytable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

![index](https://user-images.githubusercontent.com/37615468/38680739-515ab37a-3e67-11e8-9724-79adf4f597e7.jpg)

**Comment by MoneroOcean** [comment]
I merged http/json server implementation in https://github.com/MoneroOcean/xmr-node-proxy/commit/e683844e17cb93b18503c7cee961710c046187ad

**Comment by MoneroOcean** [comment]
Redesigned reports to remove JavaScript from them, so they can be viewed by lynx text browser.

**Comment by MoneroOcean** [comment]
You can see worker API dump on http://127.0.0.1:8081/json (if you enable that in config.json, see config_example.json)

**Comment by MoneroOcean** [comment]
Web page with stats can be viewed in text mode by lynx web browser: `lynx http://127.0.0.1:8081`
