### ISSUE TITLE
miner.logString is not a function

### ISSUE THREAD

**Issue by ChristophGoth** [MoneroOcean/xmr-node-proxy#61]
Getting following error after Update (New Git Clone, just copied Config) from 0.2.0 to 0.2.1:

1|proxy    | 2018-08-20 12:05:40:315 +02:00: TypeError: miner.logString is not a function
1|proxy    |     at Server.http.createServer (/home/nodeproxy/xmr-node-proxy/proxy.js:1227:26)
1|proxy    |     at emitTwo (events.js:126:13)
1|proxy    |     at Server.emit (events.js:214:7)
1|proxy    |     at parserOnIncoming (_http_server.js:619:12)
1|proxy    |     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)

After this, nodeproxy-service is restarting, occuring every minute.

**Comment by ChristophGoth** [comment]
Rolling back from Commit 5e3c09d313c3d58bbb4a556895f844b3488aeb31 fixes.

**Comment by MoneroOcean** [comment]
Thanks for report! Could you please check that https://github.com/MoneroOcean/xmr-node-proxy/commit/05822a8012c3b76f300d6e5d86637bcbf726d124 fixes that?

**Comment by ChristophGoth** [comment]
Looks quite good, thanks for the fix.

**Comment by MoneroOcean** [comment]
You are welcome.
