### ISSUE TITLE
Ubuntu 18.04 LTS support.

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmr-node-proxy#63]
Hello,
Is XNP compatible with Ubuntu 18.04LTS?
Thank you.

**Comment by djfinch** [comment]
![image](https://user-images.githubusercontent.com/13107713/44596784-ce88b480-a7cd-11e8-819f-5c9edcf45487.png)

**Comment by MoneroOcean** [comment]
Should be.

**Comment by alexdaums** [comment]
Ok thanks!
