### ISSUE TITLE
XTL (and some other algos) proxy doesn't work.

### ISSUE THREAD

**Issue by old-mikser** [MoneroOcean/xmr-node-proxy#69]
Stellite proxy returns every share as bad. 
Tested with cryptopool.space and hashwault pools with XMR-STAK miner.
STAK works as expected without proxy.

UPD: Also looks like heavy proxy doesnt work also. But in this case proxy says "Failed to parse block" and restarts. Tested cryptonightheavy and lok coins. Not sure about others, gonna test tomorrow.

P.S. xmr and msr coins are working fine.

**Comment by 7evenmikser** [comment]
@djfinch really weired... I updated to the latest version of the proxy and just changing algo setup and pool addresses (on both sides proxy and miner) - works with masari and moreno (v7 and cn fast) but not with loki and xtl...

**Comment by 7evenmikser** [comment]
Also got "Not active block template" for bittube coin and "Error: You must provide one argument." while sending job to pool with XHV...
Am I doing something wrong?

**Comment by MoneroOcean** [comment]
Really strange. Works fine on MO pool. Can you please show XNP config (without wallet address)?
