### ISSUE TITLE
17 Vulnerabilities Found

### ISSUE THREAD

**Issue by CryptoBroke550** [MoneroOcean/xmr-node-proxy#74]
Hello, after restarting the proxy I see 17 Vulnerabilities and to Run NPM audit fix.
I'm using Docker on windows 10 and not sure how to do this, do you have instructions I can follow?
Thanks.

**Comment by Spudz76** [comment]
`npm` is a touch... touchy - with what it considers vulnerable or etc - not really problems / usually theoretical / may be bugs in unused library features thus the holes don't matter (it doesn't throw messages based on what methods were used, more generic by package entirety)

Also they are messages from upstream dependencies so the right place to fix them is wherever those are

**Comment by CryptoBroke550** [comment]
Thanks Spudz76, I'm new to mining, docker and not much of a Linux user so lots of learning.
Was not sure I created an issue after stopping and starting the proxy to get it to update.
I have only had it running for about 10 days and wanted to make sure things are good for the Fork.

**Comment by MoneroOcean** [comment]
Yeah, it is almost impossible to fix all of these. Not sure if that is really important to fix especially if your proxy is not visible to outside world. I usually fix that only if github reports it to my repo. These are more or less important I think.
