### ISSUE TITLE
TypeError: Cannot read property 'shareTargetTime'

### ISSUE THREAD

**Issue by Sevilla404** [MoneroOcean/xmr-node-proxy#75]
Im working with somes miners (xmrig, xmr-stak) and some miner shutdown my proxy with this error on xmr-node-proxy

1|proxy    | 2018-10-15 12:32 -05:00: TypeError: Cannot read property 'shareTargetTime' of undefined
1|proxy    |     at Miner.updateDifficulty (/home/nodeproxy/xmr-node-proxy/proxy.js:974:129)
1|proxy    |     at Timeout._onTimeout (/home/nodeproxy/xmr-node-proxy/proxy.js:1570:39)
1|proxy    |     at ontimeout (timers.js:498:11)
1|proxy    |     at tryOnTimeout (timers.js:323:5)
1|proxy    |     at Timer.listOnTimeout (timers.js:290:5)
1|proxy    | 2018-10-15 12:32 -05:00: Worker 23989 died with code: 1, and signal: null

**Comment by MoneroOcean** [comment]
Please refer to https://github.com/MoneroOcean/xmr-node-proxy/issues/55
