### ISSUE TITLE
Sort order for hashrate on  webpage does not sort correctly by value

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#79]
When sortying by hashrate, it appears to be sorting by text value, not by numerical value. For example it shows 139h/s, 170h/s, 80h/s.

**Comment by MrCook1es** [comment]
I confirm, same issue.
**XNP v0.3.4 Hashrate Monitor** sort by default the "Connected" column.
If I sort by "Hashrate" column, it shows a random order.


Second question: is it possible to sort by defoult by "Name"column?
How can I change it?

Thanks

**Comment by MrCook1es** [comment]
@MoneroOcean any help?

**Comment by MrCook1es** [comment]
^UP^

**Comment by MrCook1es** [comment]
^UP^

**Comment by MrCook1es** [comment]
@MoneroOcean 
After updating to "XNP v0.8.1 Hashrate Monitor" I confirm again the presence of reported errors.

**Comment by djfinch** [comment]
It's because hashrate result in table cell is not INT but STRING. I can live with that...
You can remove ` + " H/s"` from [this](https://github.com/MoneroOcean/xmr-node-proxy/blob/master/proxy.js#L1269) line and maybe convert miner.avgSpeed to INT...

**Comment by MrCook1es** [comment]
thanks @djfinch 
also for me H / S sorting is not fundamental to me.
Instead it would be great to have the ability to set the sort order by default for "Name".
Every time I set the sort for "Name", the sorting disappears at the next refresh.

**Comment by MrCook1es** [comment]
Instead it would be great to have the ability to set the sort order by default for "Name".
Every time I set the sort for "Name", the sorting disappears at the next refresh.
