### ISSUE TITLE
Random proxy worker crash and recreation

### ISSUE THREAD

**Issue by dirtydavemcgee** [MoneroOcean/xmr-node-proxy#8]
Seen randomly when workers connect to pool
Worker config files only have proxy address and password variables set
1|proxy    | 04-23-18 05:31 +00:00: TypeError: Cannot read property 'length' of undefined
1|proxy    |     at Server.http.createServer (/home/ubuntu/xmr-node-proxy/proxy.js:1025:15)
1|proxy    |     at emitTwo (events.js:106:13)
1|proxy    |     at Server.emit (events.js:191:7)
1|proxy    |     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
1|proxy    |     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
1|proxy    | 04-23-18 05:31 +00:00: Cluster master setting up 1 workers...
1|proxy    | 04-23-18 05:31 +00:00: Worker 30444 is online
1|proxy    | 04-23-18 05:31 +00:00: Master connected to pool: gulf.moneroocean.stream
1|proxy    | 04-23-18 05:31 +00:00: Received new block template on 1557298 height from gulf.moneroocean.stream
1|proxy    | 04-23-18 05:31 +00:00: Started server on port: 8080
1|proxy    | 04-23-18 05:31 +00:00: Started server on port: 8443
1|proxy    | 04-23-18 05:31 +00:00: Started server on port: 3333
1|proxy    | 04-23-18 05:31 +00:00: The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN

**Comment by MoneroOcean** [comment]
Should be fixed by https://github.com/MoneroOcean/xmr-node-proxy/commit/bd2b1cb10c5d71becbf14f07c678746650591c10
Please check.

**Comment by dirtydavemcgee** [comment]
Will check in some 12 hours. Thanks

**Comment by bobbieltd** [comment]
I tested latest MO codes. It runs perfectly well.

**Comment by MoneroOcean** [comment]
@dirtydavemcgee do you still see this problem?

**Comment by dirtydavemcgee** [comment]
Sorry for delay in update. Problem seemsto be resolved. Thanks
