### ISSUE TITLE
XNP crash after update to 0.5.0

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#83]
After updating the proxy will not load. I'm seeing the following in the logs...
Error: /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node: undefined symbol: cnv2_mainloop_ryzen_asm

**Comment by MoneroOcean** [comment]
Please try to do update again. Is it fixed?

**Comment by KnoAll** [comment]
No change

**Comment by MoneroOcean** [comment]
Please try again and let me know.

**Comment by MoneroOcean** [comment]
Great!
