### ISSUE TITLE
XNP update error on arm7

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#86]
getting and error when updating.

`> cryptonight-hashing@7.0.0 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use                 NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use                 NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use                 NODEJS_ORG_MIRROR
make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
  SOLINK(target) Release/obj.target/cn_gpu.so
  COPY Release/cn_gpu.so
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn_gpu_arm.o
../xmrig/crypto/cn_gpu_arm.cpp: In function ‘void round_compute(const float32x4_t&, const float32x4_t                &, const float32x4_t&, const float32x4_t&, const float32x4_t&, float32x4_t&, float32x4_t&)’:
../xmrig/crypto/cn_gpu_arm.cpp:115:36: error: ‘vdivq_f32’ was not declared in this scope
     r = vaddq_f32(r, vdivq_f32(n, d));
                                    ^
../xmrig/crypto/cn_gpu_arm.cpp: In function ‘void cn_gpu_inner_arm(const uint8_t*, uint8_t*)’:
../xmrig/crypto/cn_gpu_arm.cpp:232:35: error: there are no arguments to ‘vdivq_f32’ that depend on a                 template parameter, so a declaration of ‘vdivq_f32’ must be available [-fpermissive]
         sum0 = vdivq_f32(sum0, cc2);
                                   ^
../xmrig/crypto/cn_gpu_arm.cpp:232:35: note: (if you use ‘-fpermissive’, G++ will accept your code, b                ut allowing the use of an undeclared name is deprecated)
../xmrig/crypto/cn_gpu_arm.cpp: In instantiation of ‘void cn_gpu_inner_arm(const uint8_t*, uint8_t*)                 [with unsigned int ITER = 49152u; unsigned int MASK = 2097088u; uint8_t = unsigned char]’:
../xmrig/crypto/cn_gpu_arm.cpp:240:124:   required from here
../xmrig/crypto/cn_gpu_arm.cpp:232:25: error: ‘vdivq_f32’ was not declared in this scope
         sum0 = vdivq_f32(sum0, cc2);
                ~~~~~~~~~^~~~~~~~~~~
cryptonight-hashing.target.mk:143: recipe for target 'Release/obj.target/cryptonight-hashing/xmrig/cr                ypto/cn_gpu_arm.o' failed
make: *** [Release/obj.target/cryptonight-hashing/xmrig/crypto/cn_gpu_arm.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_module                s/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions                /node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@7.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@7.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2019-02-10T20_36_51_087Z-debug.log
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command
`

**Comment by MoneroOcean** [comment]
Will look into it today.

**Comment by MoneroOcean** [comment]
Hello, can you please check it now?

**Comment by KnoAll** [comment]
Working now, thanks

**Comment by KnoAll** [comment]
Happening again.
../xmrig/crypto/cn_gpu_arm.cpp:115:36: error: ‘vdivq_f32’ was not declared in th                                     is scope
     r = vaddq_f32(r, vdivq_f32(n, d));
                                    ^
../xmrig/crypto/cn_gpu_arm.cpp: In function ‘void cn_gpu_inner_arm(const uint8_t                                     *, uint8_t*)’:
../xmrig/crypto/cn_gpu_arm.cpp:232:35: error: there are no arguments to ‘vdivq_f                                     32’ that depend on a template parameter, so a declaration of ‘vdivq_f32’ must be                                      available [-fpermissive]
         sum0 = vdivq_f32(sum0, cc2);
                                   ^
../xmrig/crypto/cn_gpu_arm.cpp:232:35: note: (if you use ‘-fpermissive’, G++ wil                                     l accept your code, but allowing the use of an undeclared name is deprecated)
../xmrig/crypto/cn_gpu_arm.cpp: In instantiation of ‘void cn_gpu_inner_arm(const                                      uint8_t*, uint8_t*) [with unsigned int ITER = 49152u; unsigned int MASK = 20970                                     88u; uint8_t = unsigned char]’:
../xmrig/crypto/cn_gpu_arm.cpp:240:124:   required from here
../xmrig/crypto/cn_gpu_arm.cpp:232:25: error: ‘vdivq_f32’ was not declared in th                                     is scope
         sum0 = vdivq_f32(sum0, cc2);
                ~~~~~~~~~^~~~~~~~~~~
cryptonight-hashing.target.mk:140: recipe for target 'Release/obj.target/crypton                                     ight-hashing/xmrig/crypto/cn_gpu_arm.o' failed
make: *** [Release/obj.target/cryptonight-hashing/xmrig/crypto/cn_gpu_arm.o] Err                                     or 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight                                     -hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8                                     .11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                     s.js:198:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/no                                     deproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bi                                     n/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@8.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@8.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                     ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2019-02-28T22_15_13_508Z-debug.log

**Comment by MoneroOcean** [comment]
Restored fix. Please try again.

**Comment by KnoAll** [comment]
Working again, thanks!

**Comment by blackrangersoftware** [comment]
Same exact issue today. Only posting output from where it breaks down. 
Since this has been "fixed" a couple of times before,
What is the fix for "error: ‘vdivq_f32’ was not declared in this scope"?

XNP installed perfectly on Ubuntu 20 Server with the exact same package.
Tried installing on a device with ARMv8 option available but is only recognized as ARMv7 apparently.
After three or four attempts at installing portions manually to get to the place where it breaks down,
I found a Japanese post that copied directly from this thread, but in neither place do I find what the solution was.
We have cloned the project so we can work from local code, so when this gets "fixed" again, it is my understanding that the changes will be able to be pulled into our local copy.

If I knew the "fix" I would push it.

Here is the final output and where I will probably have to leave this unless I find the answer somewhere else.

```
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)
default -> v8.11.3

> cryptonight-hashing@21.0.0 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/gpu/cn_gpu_arm.o
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp: In function ‘void round_compute(const float32x4_t&, const float32x4_t&, const float32x4_t&, const float32x4_t&, const float32x4_t&, float32x4_t&, float32x4_t&)’:
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp:115:36: error: ‘vdivq_f32’ was not declared in this scope
     r = vaddq_f32(r, vdivq_f32(n, d));
                                    ^
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp: In function ‘void cn_gpu_inner_arm(const uint8_t*, uint8_t*)’:
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp:232:35: error: there are no arguments to ‘vdivq_f32’ that depend on a template parameter, so a declaration of ‘vdivq_f32’ must be available [-fpermissive]
         sum0 = vdivq_f32(sum0, cc2);
                                   ^
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp:232:35: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp: In instantiation of ‘void cn_gpu_inner_arm(const uint8_t*, uint8_t*) [with unsigned int ITER = 49152u; unsigned int MASK = 2097088u; uint8_t = unsigned char]’:
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp:240:172:   required from here
../xmrig/crypto/cn/gpu/cn_gpu_arm.cpp:232:25: error: ‘vdivq_f32’ was not declared in this scope
         sum0 = vdivq_f32(sum0, cc2);
                         ^
cryptonight-hashing.target.mk:179: recipe for target 'Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/gpu/cn_gpu_arm.o' failed
make: *** [Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/gpu/cn_gpu_arm.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.111
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@21.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@21.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2020-09-12T09_46_30_335Z-debug.log
```
