### ISSUE TITLE
v0.7.0 Post-Update Issue

### ISSUE THREAD

**Issue by gr8form** [MoneroOcean/xmr-node-proxy#88]
Updated proxy late last night which was successful, re-tried again this morning and received already updated message.  Proxy is MO's build using AWS EC2 instance.  However, am getting binding issues in startup complaining it can't find the bindings file:  
1|proxy  | 2019-02-15 10:51:32:798 +00:00: Xmr-Node-Proxy (XNP) v0.7.0
1|proxy  | 2019-02-15 10:51:32:801 +00:00: Cluster master setting up 1 workers...
1|proxy  | 2019-02-15 10:51:32:810 +00:00: Error: Could not locate the bindings file. Tried:
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/build/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/build/Debug/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/out/Debug/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/Debug/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/out/Release/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/Release/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/build/default/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:  → /home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/compiled/8.11.3/linux/x64/cryptonight-hashing.node
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at bindings (/home/ubuntu/xmr-node-proxy/node_modules/bindings/bindings.js:93:9)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Object.<anonymous> (/home/ubuntu/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:1:99)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Module._compile (module.js:652:30)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Object.Module._extensions..js (module.js:663:10)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Module.load (module.js:565:32)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at tryModuleLoad (module.js:505:12)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Function.Module._load (module.js:497:3)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Module.require (module.js:596:17)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at require (internal/module.js:11:18)
1|proxy  | 2019-02-15 10:51:32:810 +00:00:     at Object.<anonymous> (/home/ubuntu/xmr-node-proxy/lib/xmr.js:2:22)

Thanks in advance!

**Comment by bobbieltd** [comment]
Try 
cd xmr-node-proxy
npm install

**Comment by gr8form** [comment]
Thanks for the suggestion, gave it a shot; same result, no joy.
ubuntu_xxxxxxx:~/xmr-node-proxy$ npm install
up to date in 1.795s

**Comment by gr8form** [comment]
This is now resolved.  Leaving steps taken in case it helps others:

1. Increased swap space on EC2 instance by 1GB - https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

2. Pulled git repo for a direct update - 
cd xmr-node-proxy
git pull https://github.com/MoneroOcean/xmr-node-proxy.git && npm update

3. Re-installed proxy using instructions:
source ~/.bashrc
cd ~/xmr-node-proxy/
pm2 start proxy.js --name=proxy --log-date-format="YYYY-MM-DD HH:mm:ss:SSS Z"
pm2 save

4. Check on logs revealed an issue still with not finding cryptonotefork; resolved by - 
./update.sh

So, I believe my EC2 instance had insufficient swap space which somehow corrupted the update; YMMV.
