### ISSUE TITLE
Rejected Share

### ISSUE THREAD

**Issue by rampso** [MoneroOcean/xmr-node-proxy#89]
I recently started using this and xmr-stak to mine conceal coin at the following pool (https://conceal.herominers.com/#). I was hosting the proxy on a vps from OVH but just moved to AWS a few days ago. Ever since I moved to the AWS I can't get mining conceal to work properly. When mining directly to the pool with stak all works as expected but when I point xmr-stak to the proxy all shares get rejected. Anyone have any ideas why this happens or can test on their end to see if it's isolated to me only? I did attempt a reinstall but still same issue. Mining monero works fine so have switched to that for the time being. 

proxy config below
---
{
"pools": [
{
"hostname": "conceal.herominers.com",
"port":10361,
"ssl": false,
"allowSelfSignedSSL": false,
"share": 100,
"username": "ccx address",
"password": "Proxy",
"keepAlive": true,
"algo": "cryptonight/msr",
"blob_type": "cryptonote2",
"default": true
   
  }
],

  "listeningPorts": [
    {
      "port": 3434,
      "ssl": false,
      "diff": 25000
    }
  ],
  "bindAddress": "0.0.0.0",
  "developerShare": 1,
  "daemonAddress": "127.0.0.1:18081",
  "accessControl": {
    "enabled": false,
    "controlFile": "accessControl.json"
  },
  "httpEnable": true,
  "httpAddress": "0.0.0.0",
  "httpPort": "8081",
  "httpUser": "username",
  "httpPass": "password",
  "addressWorkerID": false,
  "minerInactivityTime": 1,
  "keepOfflineMiners": 0,
  "refreshTime": 1,
  "theme": "dark",
  "coinSettings": {
    "xmr":{
      "minDiff": 10100,
      "maxDiff": 300000,
      "shareTargetTime": 15
    }
  }
}

**Comment by djfinch** [comment]
Hi, blob is cryptonote, not cryptonote2...

**Comment by djfinch** [comment]
{
  "pools": [
    {
      "hostname": "conceal.herominers.com",
      "algo": "cn/msr",
      "blob_type": "cryptonote",
    }
  ],
  "coinSettings": {
    "xmr":{
      "minDiff": 10,
      "maxDiff": 100000,
      "shareTargetTime": 10
    }
  }
}

```
2019-02-21 09:05 +00:00: Submitted 1 share(s) of 25000 hashes to conceal.herominers.com pool
```

**Comment by rampso** [comment]
Submitted share of 9615 hashes to conceal.herominers.com pool

Wow thanks for pointing that out.  The pools site listed settings for proxy to use cryptonote2 for some reason.

**Comment by djfinch** [comment]
wrong config example reported on their discord channel... thanks for spotting this.
