### ISSUE TITLE
Error in new v0.9

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#93]
updated OK with no errors on ARMv7, but not loading in pm2.
 proxy > 2019-03-06 15:30:40:821 -08:00: Xmr-Node-Proxy (XNP) v0.9.0           x
x                                 xx proxy > 2019-03-06 15:30:40:854 -08:00: Cluster master setting up 4           x
x                                 xx workers...                                                                    x
x                                 xx proxy > 2019-03-06 15:30:41:143 -08:00: Error: /home/nodeproxy/xmr-node-prox  x
x                                 xx y/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node:    x
x                                 xx undefined symbol: CryptonightR_instruction_mov0                               x
x                                 xx proxy >     at Object.Module._extensions..node (module.js:681:18)             x
x                                 xx proxy >     at Module.load (module.js:565:32)                                 x
x                                 xx proxy >     at tryModuleLoad (module.js:505:12)                               x
x                                 xx proxy >     at Function.Module._load (module.js:497:3)                        x
x                                 xx proxy >     at Module.require (module.js:596:17)                              x
x                                 xx proxy >     at require (internal/module.js:11:18)                             x
x                                 xx proxy >     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/binding  x
x                                 xx s/bindings.js:81:44)                                                          x
x                                 xx proxy >     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modul  x
x                                 xx es/cryptonight-hashing/index.js:1:99)                                         x
x                                 xx proxy >     at Module._compile (module.js:652:30)                             x
x                                 xx proxy >     at Object.Module._extensions..js (module.js:663:10)               x
x                                 xx PM2 > App [proxy] with id [1] and pid [22347], exited with code [1] via       x
x                                 xx signal [SIGINT]                                                               x
x                                 xx PM2 > Starting execution sequence in -fork mode- for app name:proxy id:1      x
x                                 xx PM2 > App name:proxy id:1 online                                              x
x                                 xx proxy > 2019-03-06 15:30:43:060 -08:00: Error: /home/nodeproxy/xmr-node-prox  x
x                                 xx y/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node:    x
x                                 xx undefined symbol: CryptonightR_instruction_mov0                               x
x                                 xx proxy >     at Object.Module._extensions..node (module.js:681:18)             x
x                                 xx proxy >     at Module.load (module.js:565:32)                                 x
x                                 xx proxy >     at tryModuleLoad (module.js:505:12)                               x
x                                 xx proxy >     at Function.Module._load (module.js:497:3)                        x
x                                 xx proxy >     at Module.require (module.js:596:17)                              x
x                                 xx proxy >     at require (internal/module.js:11:18)                             x
x                                 xx proxy >     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/binding  x
x                                 xx s/bindings.js:81:44)                                                          x
x                                 xx proxy >     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modul  x
x                                 xx es/cryptonight-hashing/index.js:1:99)                                         x
x                                 xx proxy >     at Module._compile (module.js:652:30)                             x
x                                 xx proxy >     at Object.Module._extensions..

**Comment by MoneroOcean** [comment]
Ops. Thanks! Should be already fixed.

**Comment by KnoAll** [comment]
OK, working. thanks! onward towards the fork!
